ALTER TABLE tasks ADD COLUMN importance VARCHAR(50);
ALTER TABLE tasks ADD COLUMN description TEXT;
ALTER TABLE tasks ADD COLUMN hide_until TIMESTAMP NULL;
ALTER TABLE tasks ADD COLUMN completed_at TIMESTAMP NULL;
